steps:
- name: node:14
  entrypoint: npm
  args: ['install']
- name: node:14
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-d', '-r', './dist/', 'gs://share-reader-front/']
